import { jsPDF } from 'jspdf';

export function downloadReport(sessionData, profile) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('HealMotion', pw / 2, y, { align: 'center' });
  y += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Clinical Rehabilitation Progress Report', pw / 2, y, { align: 'center' });
  y += 12;
  doc.setDrawColor(225, 137, 79);
  doc.line(20, y, pw - 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Information', 20, y); y += 7;
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${profile?.name || 'Anonymous'}`, 25, y); y += 5;
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 25, y); y += 10;

  doc.setFont('helvetica', 'bold');
  doc.text('Exercise Summary', 20, y); y += 7;

  for (const ex of (sessionData.exercises || [])) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`• ${ex.exerciseId || 'Exercise'}`, 25, y); y += 5;
    doc.setFont('helvetica', 'normal');
    doc.text(`  Reps: ${ex.repsCompleted || 0}/${ex.targetReps || '-'}`, 30, y); y += 4;
    if (ex.avgROM != null) { doc.text(`  Avg ROM: ${ex.avgROM.toFixed(1)}°`, 30, y); y += 4; }
    if (ex.symmetryIndex != null) { doc.text(`  Symmetry: ${ex.symmetryIndex}%`, 30, y); y += 4; }
    if (ex.fatigueLevel != null) { doc.text(`  Fatigue: ${ex.fatigueLevel.toFixed(0)}%`, 30, y); y += 4; }
    if (ex.compensationsDetected > 0) { doc.text(`  Compensations: ${ex.compensationsDetected}`, 30, y); y += 4; }
    y += 4;
  }

  y += 5;
  doc.setDrawColor(225, 137, 79);
  doc.line(20, y, pw - 20, y); y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Clinical Insights', 20, y); y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  for (const ex of (sessionData.exercises || [])) {
    if (ex.symmetryIndex != null && ex.symmetryIndex < 90) {
      doc.text(`• Asymmetry detected (${ex.symmetryIndex}%). Focus on weaker side.`, 25, y); y += 5;
    }
    if (ex.fatigueLevel > 30) {
      doc.text(`• Significant fatigue (${ex.fatigueLevel.toFixed(0)}%). Consider reducing volume.`, 25, y); y += 5;
    }
    if (ex.compensationsDetected > 2) {
      doc.text(`• Frequent compensation (${ex.compensationsDetected}x). Possible pain avoidance.`, 25, y); y += 5;
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by HealMotion — All data processed on-device', pw / 2, 285, { align: 'center' });

  doc.save(`HealMotion_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
